[package]
name = "print-programs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpf-api = "0.1.1"
bpf-script = "0.1.2"
btf = "0.3.0"
btf-derive = "0.3.0"
