[package]
name = "print-programs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bpf-api = "0.2"
bpf-script = "0.5"
bpf-script-derive = "0.5"
btf = "0.4"
